---

# ------------ Install Poetry (non-root user scope) -------------- #

- name: Download and run Poetry installer using Python {{ upgrade_python3 }}
  ansible.builtin.shell: |
    curl -sSL https://install.python-poetry.org | python{{ upgrade_python3 }} -
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/poetry"
  become: false # user-scope

- name: Ensure Poetry is in PATH (for future sessions)
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="{{ ansible_env.HOME }}/.local/bin:$PATH"'
    insertafter: EOF
    state: present
  become: false
