---

# ------------------ Install Open WebUI ------------------ #
- name: Run Open WebUI container. It might take a while...
  community.docker.docker_container:
    name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    volumes:
      - open-webui-data:/app/backend/data
    env:
      OLLAMA_BASE_URL: "http://{{ hostvars['llm_node']['ansible_host'] }}:11434" # connect to Ollama listening url
    restart_policy: always
  environment:
    # The community.docker plugin uses the Docker SDK for Python, which relies on the DOCKER_HOST environment variable
    DOCKER_HOST: "unix:///var/run/docker.sock"
  become: true
