---

# ------------------ Install smol-agent ------------------ #
- name: Create a virtual environment for smol-agent using python{{ upgrade_python3 }}
  ansible.builtin.command: python{{ upgrade_python3 }} -m venv {{ ansible_env.HOME }}/venv/smol-agent-venv
  args:
    creates: "{{ ansible_env.HOME }}/venv/smol-agent-venv/bin/activate"
  become: false

- name: Install smolagents and required dependencies inside virtualenv
  ansible.builtin.pip:
    name: "{{ smolagent_dependencies }}"
    virtualenv: "{{ ansible_env.HOME }}/venv/smol-agent-venv"
    virtualenv_python: "python{{ upgrade_python3 }}"
    state: present

- name: Render ollama_agent.py with Local LLM node IP
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/work/{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - { src: 'openai_agent.py.j2', dest: 'openai_agent.py' }
    - { src: 'ollama_agent.py.j2', dest: 'ollama_agent.py' }

- name: Create a launcher script for smolagent
  ansible.builtin.copy:
    dest: /usr/local/bin/smolagent
    mode: '0755'
    content: |
      #!/bin/bash
      source {{ ansible_env.HOME }}/venv/smol-agent-venv/bin/activate
      exec {{ ansible_env.HOME }}/venv/smol-agent-venv/bin/smolagent "$@"
  become: true
