---
# -------- Install smol-developer (non-root user scope) ---------- #

- name: Remove /tmp/smol-ai folder if exists
  ansible.builtin.file:
    path: /tmp/smol-ai
    state: absent
  become: false
  
- name: Clone smol-developer repository
  ansible.builtin.git:
    repo: https://github.com/smol-ai/developer.git
    dest: /tmp/smol-ai
    version: main
    force: true # fresh clone everytime, not strictly idempotent
  become: false

- name: Overwrite broken pyproject.toml with fixed version
  ansible.builtin.copy:
    src: files/pyproject.toml
    dest: /tmp/smol-ai/pyproject.toml
    mode: '0644'
    owner: "{{ ansible_user }}"
  become: false

- name: Regenerate poetry.lock after updating pyproject.toml
  ansible.builtin.command: poetry lock
  args:
    chdir: /tmp/smol-ai
  changed_when: false

# Need a pythom project to do this
- name: Set poetry to use Python {{ upgrade_python3 }}
  ansible.builtin.shell: poetry env use python{{ upgrade_python3 }}
  args:
    chdir: /tmp/smol-ai
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  become: false

- name: Install smol-developer with poetry
  ansible.builtin.shell: poetry install
  args:
    chdir: /tmp/smol-ai
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  become: false
