---
# tasks file for llm_stack

# ------------------ Install Ollama ------------------ #
- name: Run install Ollama tasks
  ansible.builtin.include_tasks: install_ollama.yml

# ------------------ Pull LLM ------------------ #
- name: Run pull LLM tasks
  ansible.builtin.include_tasks: pull_llm.yml

# -------- Install smol-agent (non-root user scope) -------- #
- name: Run install smol-agent tasks
  ansible.builtin.include_tasks: install_smol-agent.yml

# ------------------ Install Open WebUI ------------------ #
- name: Run install Open WebUI tasks
  ansible.builtin.include_tasks: install_openwebui.yml

# ------------------ Assertions ------------------ #
- name: Run smol-agent assertion
  ansible.builtin.include_tasks: assert_smol-agent.yml