---

all:
  vars:
    ansible_user: iacuser
    upgrade_python3: 3.11
    ollama_model: 'gemma:2b'
    dev_tools:
      - epel-release
      - git
      - curl
      - make
      - gcc
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - wget
    
    smolagent_dependencies:
      - smolagents[litellm]

    # Give LLM Code Generation Prompt/Agentic Task Prompt 
    agentic_prompt: "Only write a simple Python function that takes two numbers and returns their sum. Do not use web or external tools."
    max_steps: 1  # use smaller number for simple task in order to avoid extra steps and task drift

  children:
    local_llm:
      hosts:
        llm_node:
          ansible_host: 192.168.184.138
          # ansible_host: 192.168.184.146
          ansible_connection: ssh



