---

all:
  vars:
    ansible_user: iacuser
    upgrade_python3: 3.11
    ollama_model: 7b-instruct # smaller and instruction-tuned, CPU friendly 
    dev_tools:
      - epel-release
      - git
      - curl
      - make
      - gcc
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - wget
    
  children:
    local_llm:
      hosts:
        llm_node:
          ansible_host: 192.168.184.138
          # ansible_host: 192.168.184.146
          ansible_connection: ssh



